## Basic Functions

In [1]:
import numpy as np

In [2]:
# Numpy tutorial 2
array1 = np.array([[3,2,5,6,7],[3,5,6,7,8]], dtype='int32')
print(array1)

[[3 2 5 6 7]
 [3 5 6 7 8]]


In [3]:
array1.shape  # showing 2 rows and 5 columns

(2, 5)

In [4]:
array1.dtype # datatype of array1

dtype('int32')

In [5]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [6]:
np.ones(6).dtype

dtype('float64')

In [7]:
np.empty((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [8]:
array1

array([[3, 2, 5, 6, 7],
       [3, 5, 6, 7, 8]])

In [9]:
array1*array1


array([[ 9,  4, 25, 36, 49],
       [ 9, 25, 36, 49, 64]])

In [10]:
array1+array1

array([[ 6,  4, 10, 12, 14],
       [ 6, 10, 12, 14, 16]])

In [11]:
array1 - array1

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [12]:
array1/array1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
array1**array1

array([[      27,        4,     3125,    46656,   823543],
       [      27,     3125,    46656,   823543, 16777216]], dtype=int32)

In [14]:
np.array([12**12])

array([8916100448256], dtype=int64)

In [15]:
1/array1

array([[0.33333333, 0.5       , 0.2       , 0.16666667, 0.14285714],
       [0.33333333, 0.2       , 0.16666667, 0.14285714, 0.125     ]])

## Slicing

In [16]:
array2 = np.array([5,4,64,3,3,3])

In [17]:
arr =array2[4:6].copy()

In [18]:
arr

array([3, 3])

In [19]:
arr[0] = 9

In [20]:
array2

array([ 5,  4, 64,  3,  3,  3])

In [21]:
arr

array([9, 3])

In [22]:
array1

array([[3, 2, 5, 6, 7],
       [3, 5, 6, 7, 8]])

In [23]:
array1[0,3]

6